fix: restore invalid yaml structure and remove comments

diff --git a/k8s-app/loja.yaml b/k8s-app/loja.yaml
--- a/k8s-app/loja.yaml
+++ b/k8s-app/loja.yaml
@@ -102,21 +102,21 @@ spec:
         - command:
             - /bin/sh
             - -exc
-          - |
-            MAX_RETRIES=12
-            RETRY_INTERVAL=10
-            for i in $(seq 1 $MAX_RETRIES); do
-              echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
-              STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-              if [ $STATUSCODE -eq 200 ]; then
-                  echo "Frontend is reachable."
-                  exit 0
-              fi
-              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-              sleep $RETRY_INTERVAL
-            done
-            echo "Failed to reach frontend after $MAX_RETRIES attempts."
-            exit 1
+            - |
+              MAX_RETRIES=12
+              RETRY_INTERVAL=10
+              for i in $(seq 1 $MAX_RETRIES); do
+                echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
+                STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+                if [ $STATUSCODE -eq 200 ]; then
+                    echo "Frontend is reachable."
+                    exit 0
+                fi
+                echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+                sleep $RETRY_INTERVAL
+              done
+              echo "Failed to reach frontend after $MAX_RETRIES attempts."
+              exit 1
           name: frontend-check
           securityContext:
             allowPrivilegeEscalation: false
@@ -719,16 +719,16 @@ spec:
               path: "/_healthz"
               port: 8080
               httpHeaders:
-        - name: "Cookie"
-                    value: "shop_session-id=x-readiness-probe"
+                - name: "Cookie"
+                  value: "shop_session-id=x-readiness-probe"
           livenessProbe:
             initialDelaySeconds: 10
             httpGet:
               path: "/_healthz"
               port: 8080
               httpHeaders:
-        - name: "Cookie"
-                    value: "shop_session-id=x-liveness-probe"
+                - name: "Cookie"
+                  value: "shop_session-id=x-liveness-probe"
           env:
             - name: PORT
               value: "8080"
@@ -748,21 +748,10 @@ spec:
               value: "adservice:9555"
             - name: SHOPPING_ASSISTANT_SERVICE_ADDR
               value: "shoppingassistantservice:80"
-                  # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
-                  # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp
-                  # - name: ENV_PLATFORM
-                  #   value: "aws"
+                
             - name: ENABLE_PROFILER
               value: "0"
-                  # - name: CYMBAL_BRANDING
-                  #   value: "true"
-                  # - name: ENABLE_ASSISTANT
-                  #   value: "true"
-                  # - name: FRONTEND_MESSAGE
-                  #   value: "Replace this with a message you want to display on all pages."
-                  # As part of an optional Google Cloud demo, you can run an optional microservice called the "packaging service".
-                  # - name: PACKAGING_SERVICE_URL
-                  #   value: "" # This value would look like "http://123.123.123"
+              
           resources:
             requests:
               cpu: 100m
@@ -957,4 +946,3 @@ apiVersion: v1
 kind: ServiceAccount
 metadata:
   name: adservice
-# [END gke_release_kubernetes_manifests_microservices_demo]
